---
dist: bionic
language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get install -y silversearcher-ag
  - |
    sudo wget -O /usr/local/bin/hadolint \
      https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && \
    sudo chmod +x /usr/local/bin/hadolint
  - pip install pipenv
  - pipenv install -d --deploy
  - npm i -g npm
  - npm ci
script:
  - python3.7 tasks.py test
