---
services:
  web:
    build:
      cache_from:
        - ghcr.io/c4se-jp/martian_imperial_year_table/martian_imperial_year_table-web:latest
      context: .
      dockerfile: deployments/development/Dockerfile
    #develop:
    #  watch:
    #    - action: sync
    #      path: .
    #      target: /mnt
    image: ghcr.io/c4se-jp/martian_imperial_year_table/martian_imperial_year_table-web:latest
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    ports:
      - 5000:5000
    volumes:
      - .:/mnt
