---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - "gcr.io/${PROJECT_ID}/martian_imperial_year_table:latest"
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deployments/staging/Dockerfile
      - -t
      - "gcr.io/${PROJECT_ID}/martian_imperial_year_table:${SHORT_SHA}"
      - -t
      - "gcr.io/${PROJECT_ID}/martian_imperial_year_table:latest"
      - --cache-from
      - "gcr.io/${PROJECT_ID}/martian_imperial_year_table:latest"
      - .
    timeout: 300s
  - name: gcr.io/cloud-builders/docker
    args: [push, "gcr.io/${PROJECT_ID}/martian_imperial_year_table:${SHORT_SHA}"]
  - name: gcr.io/cloud-builders/docker
    args: [push, "gcr.io/${PROJECT_ID}/martian_imperial_year_table:latest"]
  - name: gcr.io/cloud-builders/kubectl
    entrypoint: bash
    args: [./deployments/staging/kubectl.sh]
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast1
      - CLOUDSDK_CONTAINER_CLUSTER=c4se
      - MACKEREL_APIKEY=$_MACKEREL_APIKEY
      - PROJECT_ID=$PROJECT_ID
      - SHORT_SHA=$SHORT_SHA
substitutions:
  _NAMESPACE_NAME: staging
timeout: 360s
