---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      [
        -c,
        "docker pull asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:builder || true",
      ]
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      [
        -c,
        "docker pull asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:latest || true",
      ]
  - name: python:3.12-slim
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deployments/staging/Dockerfile
      - -t
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:builder"
      # - --build-arg
      # - BUILDKIT_INLINE_CACHE=1
      - --cache-from
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:builder"
      - --target
      - builder
      - .
    # env:
    #   - DOCKER_BUILDKIT=1
    timeout: 300s
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deployments/staging/Dockerfile
      - -t
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:${SHORT_SHA}"
      - -t
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:latest"
      # - --build-arg
      # - BUILDKIT_INLINE_CACHE=1
      - --cache-from
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:builder"
      - --cache-from
      - "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:latest"
      - .
    # env:
    #   - DOCKER_BUILDKIT=1
    timeout: 300s
  - name: gcr.io/cloud-builders/docker
    args: [push, "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:builder"]
  - name: gcr.io/cloud-builders/docker
    args:
      [push, "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:${SHORT_SHA}"]
  - name: gcr.io/cloud-builders/docker
    args: [push, "asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/martian_imperial_year_table:latest"]
  - name: gcr.io/cloud-builders/kubectl
    entrypoint: bash
    args: [./deployments/staging/kubectl.sh]
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast1
      - CLOUDSDK_CONTAINER_CLUSTER=c4se-5
      - MACKEREL_APIKEY=$_MACKEREL_APIKEY
      - PROJECT_ID=$PROJECT_ID
      - SHORT_SHA=$SHORT_SHA
substitutions:
  _NAMESPACE_NAME: martian-imperial-year-table-staging
timeout: 900s
