---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: martian-imperial-year-table-staging
commonLabels:
  app: martian-imperial-year-table
patchesStrategicMerge:
  - ing.yaml
  - issuer.yaml
secretGenerator:
  - files:
      - MACKEREL_APIKEY=secret/MACKEREL_APIKEY
    name: martian-imperial-year-table
    type: Opaque
resources:
  - ../base/
