---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: martian-imperial-year-table
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: martian-imperial-year-table
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: web
          image: gcr.io/c4se-197915/martian_imperial_year_table:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ops/heartbeat
              port: 5000
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
