---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: martian-imperial-year-table
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: martian-imperial-year-table
  targetCPUUtilizationPercentage: 80
