---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: martian-imperial-year-table
resources:
  - deploy.yaml
  - hpa.yaml
  - ing.yaml
  - mackerel-agent-config.yaml
  - pdb.yaml
  - svc.yaml
