---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mackerel-agent-config
data:
  mackerel.yaml: |
    roles:
      - martian-imperial-year-table:web
    readinessProbe:
      http:
        path: /ops/heartbeat
        port: 5000
