---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: martian-imperial-year-table-production
commonLabels:
  app: martian-imperial-year-table
bases:
  - ../base/
patchesStrategicMerge:
  - ing.yaml
secretGenerator:
  - name: martian-imperial-year-table
    files:
      - MACKEREL_APIKEY=secret/MACKEREL_APIKEY
    type: Opaque
