---
name: Deploy AWS CDK

"on":
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      CERTIFICATE_ARN:
        required: true
      HOSTED_ZONE_ID:
        required: true
      VITE_GA_MEASUREMENT_ID:
        required: false
      MACKEREL_CLIENT_TOKEN:
        required: false
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: cdk-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    environment:
      name: production
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION: ap-northeast-1
      HOSTED_ZONE_DOMAIN_NAME: c4se.jp
      SITE_DOMAIN_NAME: martian-imperial-year-table.c4se.jp
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Node.jsを使ふ
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version: 24

      - name: 依存するlibraryを入れる
        run: npm ci

      - name: Web siteとwidgetをbuildする
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
          VITE_MACKEREL_CLIENT_TOKEN: ${{ secrets.MACKEREL_CLIENT_TOKEN }}
          VITE_MACKEREL_DEPLOYMENT_ENVIRONMENT: production
          VITE_MACKEREL_SERVICE_VERSION: ${{ github.sha }}
        run: npm run build

      - name: AWSに認可をとる
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDKの依存するlibraryを入れる
        run: npm install --prefix cdk

      - name: CDK deploy
        env:
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          MACKEREL_DEPLOYMENT_ENVIRONMENT: production
          MACKEREL_SERVICE_VERSION: ${{ github.sha }}
        run: |
          npx cdk deploy --require-approval never \
            -c certificateArn="${CERTIFICATE_ARN}" \
            -c hostedZoneDomainName="${HOSTED_ZONE_DOMAIN_NAME}" \
            -c hostedZoneId="${HOSTED_ZONE_ID}" \
            -c mackerelDeploymentEnvironment="${MACKEREL_DEPLOYMENT_ENVIRONMENT}" \
            -c mackerelServiceVersion="${MACKEREL_SERVICE_VERSION}" \
            -c siteDomainName="${SITE_DOMAIN_NAME}" \
            -c siteAssetsPath="${GITHUB_WORKSPACE}/dist"
        working-directory: cdk
